/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureResource } from './FeatureResource';
import {
    FeatureResourceFromJSON,
    FeatureResourceFromJSONTyped,
    FeatureResourceToJSON,
    FeatureResourceToJSONTyped,
} from './FeatureResource';
import type { NearPlaceResource } from './NearPlaceResource';
import {
    NearPlaceResourceFromJSON,
    NearPlaceResourceFromJSONTyped,
    NearPlaceResourceToJSON,
    NearPlaceResourceToJSONTyped,
} from './NearPlaceResource';
import type { TypeResource } from './TypeResource';
import {
    TypeResourceFromJSON,
    TypeResourceFromJSONTyped,
    TypeResourceToJSON,
    TypeResourceToJSONTyped,
} from './TypeResource';
import type { RentDurationResource } from './RentDurationResource';
import {
    RentDurationResourceFromJSON,
    RentDurationResourceFromJSONTyped,
    RentDurationResourceToJSON,
    RentDurationResourceToJSONTyped,
} from './RentDurationResource';
import type { MemberResource } from './MemberResource';
import {
    MemberResourceFromJSON,
    MemberResourceFromJSONTyped,
    MemberResourceToJSON,
    MemberResourceToJSONTyped,
} from './MemberResource';
import type { CategoryResource } from './CategoryResource';
import {
    CategoryResourceFromJSON,
    CategoryResourceFromJSONTyped,
    CategoryResourceToJSON,
    CategoryResourceToJSONTyped,
} from './CategoryResource';
import type { LocationResource } from './LocationResource';
import {
    LocationResourceFromJSON,
    LocationResourceFromJSONTyped,
    LocationResourceToJSON,
    LocationResourceToJSONTyped,
} from './LocationResource';
import type { ImagesResource } from './ImagesResource';
import {
    ImagesResourceFromJSON,
    ImagesResourceFromJSONTyped,
    ImagesResourceToJSON,
    ImagesResourceToJSONTyped,
} from './ImagesResource';

/**
 * 
 * @export
 * @interface ListingResource
 */
export interface ListingResource {
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ListingResource
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ListingResource
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    floor: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    surface: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    minDuration: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    numberRooms: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListingResource
     */
    numberPersons: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ListingResource
     */
    isReady: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ListingResource
     */
    isNegotiable: boolean;
    /**
     * Whether the listing has an active boost applied.
     * @type {string}
     * @memberof ListingResource
     */
    isBoosted: string;
    /**
     * 'boost_level' => $this->boost_level,
     * @type {string}
     * @memberof ListingResource
     */
    moderationStatus: string;
    /**
     * 
     * @type {string}
     * @memberof ListingResource
     */
    image: string;
    /**
     * BelongsTo
     * @type {RentDurationResource}
     * @memberof ListingResource
     */
    rentDuration?: RentDurationResource;
    /**
     * 
     * @type {TypeResource}
     * @memberof ListingResource
     */
    type?: TypeResource;
    /**
     * 
     * @type {LocationResource}
     * @memberof ListingResource
     */
    location?: LocationResource;
    /**
     * Many To Many
     * @type {Array<CategoryResource>}
     * @memberof ListingResource
     */
    categories?: Array<CategoryResource>;
    /**
     * 
     * @type {Array<FeatureResource>}
     * @memberof ListingResource
     */
    features?: Array<FeatureResource>;
    /**
     * 
     * @type {Array<NearPlaceResource>}
     * @memberof ListingResource
     */
    nearPlaces?: Array<NearPlaceResource>;
    /**
     * 
     * @type {Array<MemberResource>}
     * @memberof ListingResource
     */
    members?: Array<MemberResource>;
    /**
     * 
     * @type {Array<ImagesResource>}
     * @memberof ListingResource
     */
    images?: Array<ImagesResource>;

    ratingAvg: number,
    reviewsCount: number,
    views: 0,
    /**
     * 
     * @type {Date}
     * @memberof ListingResource
     */
    timePost: Date | null;
}




/**
 * Check if a given object implements the ListingResource interface.
 */
export function instanceOfListingResource(value: object): value is ListingResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('floor' in value) || value['floor'] === undefined) return false;
    if (!('surface' in value) || value['surface'] === undefined) return false;
    if (!('minDuration' in value) || value['minDuration'] === undefined) return false;
    if (!('numberRooms' in value) || value['numberRooms'] === undefined) return false;
    if (!('numberPersons' in value) || value['numberPersons'] === undefined) return false;
    if (!('isReady' in value) || value['isReady'] === undefined) return false;
    if (!('isNegotiable' in value) || value['isNegotiable'] === undefined) return false;
    if (!('isBoosted' in value) || value['isBoosted'] === undefined) return false;
    if (!('moderationStatus' in value) || value['moderationStatus'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('timePost' in value) || value['timePost'] === undefined) return false;
    return true;
}

export function ListingResourceFromJSON(json: any): ListingResource {
    return ListingResourceFromJSONTyped(json, false);
}

export function ListingResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'price': json['price'],
        'floor': json['floor'],
        'surface': json['surface'],
        'minDuration': json['min_duration'],
        'numberRooms': json['number_rooms'],
        'numberPersons': json['number_persons'],
        'isReady': json['is_ready'],
        'isNegotiable': json['is_negotiable'],
        'isBoosted': json['is_boosted'] ?? '0',
        'moderationStatus': json['moderation_status'],
        'image': json['image'],
        'rentDuration': json['rent_duration'] == null ? undefined : RentDurationResourceFromJSON(json['rent_duration']),
        'type': json['type'] == null ? undefined : TypeResourceFromJSON(json['type']),
        'location': json['location'] == null ? undefined : LocationResourceFromJSON(json['location']),
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryResourceFromJSON)),
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(FeatureResourceFromJSON)),
        'nearPlaces': json['near_places'] == null ? undefined : ((json['near_places'] as Array<any>).map(NearPlaceResourceFromJSON)),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(MemberResourceFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImagesResourceFromJSON)),
        'ratingAvg': json['rating_avg'],
        'reviewsCount': json['reviews_count'],
        'views': json['views'],
        'timePost': (json['time_post'] == null ? null : new Date(json['time_post'])),
    };
}

export function ListingResourceToJSON(json: any): ListingResource {
    return ListingResourceToJSONTyped(json, false);
}

export function ListingResourceToJSONTyped(value?: ListingResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'price': value['price'],
        'floor': value['floor'],
        'surface': value['surface'],
        'min_duration': value['minDuration'],
        'number_rooms': value['numberRooms'],
        'number_persons': value['numberPersons'],
        'is_ready': value['isReady'],
        'is_negotiable': value['isNegotiable'],
        'is_boosted': value['isBoosted'],
        'moderation_status': value['moderationStatus'],
        'image': value['image'],
        'rent_duration': RentDurationResourceToJSON(value['rentDuration']),
        'type': TypeResourceToJSON(value['type']),
        'location': LocationResourceToJSON(value['location']),
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryResourceToJSON)),
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(FeatureResourceToJSON)),
        'near_places': value['nearPlaces'] == null ? undefined : ((value['nearPlaces'] as Array<any>).map(NearPlaceResourceToJSON)),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(MemberResourceToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImagesResourceToJSON)),
        'time_post': value['timePost'] == null ? value['timePost'] : value['timePost'].toISOString(),
    };
}

